export const moviesArray = [
  {
    country: "США",
    director: "Director 1",
    duration: 107,
    year: 2022,
    description: "This is test description 1",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 1,
    nameRU: "33 слова о дизайне",
    nameEN: "Test film 1",
  },
  {
    country: "США",
    director: "Director 1",
    duration: 107,
    year: 2022,
    description: "This is test description 1",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 122,
    nameRU: "33 слова о дизайне22",
    nameEN: "Test film 1",
  },
  {
    country: "США",
    director: "Director 1",
    duration: 107,
    year: 2022,
    description: "This is test description 1",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 1222,
    nameRU: "33 слова о дизайне444",
    nameEN: "Test film 1",
  },
  {
    country: "США",
    director: "Director 1",
    duration: 107,
    year: 2022,
    description: "This is test description 1",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 155,
    nameRU: "33 слова о дизайне455",
    nameEN: "Test film 1",
  },
  {
    country: "США",
    director: "Director 2",
    duration: 87,
    year: 2022,
    description: "This is test description 2",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 2,
    nameRU: "Тестовый фильм 2",
    nameEN: "Test film 2",
  },
  {
    country: "США",
    director: "Director 3",
    duration: 68,
    year: 2023,
    description: "This is test description 3",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 3,
    nameRU: "Тестовый фильм 3",
    nameEN: "Test film 3",
  },
  {
    country: "США",
    director: "Director 4",
    duration: 95,
    year: 2024,
    description: "This is test description 4",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 4,
    nameRU: "Тестовый фильм 4",
    nameEN: "Test film 4",
  },
  {
    country: "США",
    director: "Director 4",
    duration: 95,
    year: 2024,
    description: "This is test description 4",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 5,
    nameRU: "Тестовый фильм 5",
    nameEN: "Test film 4",
  },
  {
    country: "США",
    director: "Director 4",
    duration: 95,
    year: 2024,
    description: "This is test description 4",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 6,
    nameRU: "Тестовый фильм 6",
    nameEN: "Test film 4",
  },
  {
    country: "США",
    director: "Director 4",
    duration: 95,
    year: 2024,
    description: "This is test description 4",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 7,
    nameRU: "Тестовый фильм 7",
    nameEN: "Test film 4",
  },
  {
    country: "США",
    director: "Director 4",
    duration: 95,
    year: 2024,
    description: "This is test description 4",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 8,
    nameRU: "Тестовый фильм 8",
    nameEN: "Test film 4",
  },
  {
    country: "США",
    director: "Director 4",
    duration: 95,
    year: 2024,
    description: "This is test description 4",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 44,
    nameRU: "Тестовый фильм 9",
    nameEN: "Test film 4",
  },
  {
    country: "США",
    director: "Director 4",
    duration: 95,
    year: 2024,
    description: "This is test description 4",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 9,
    nameRU: "Тестовый фильм 10",
    nameEN: "Test film 4",
  },
  {
    country: "США",
    director: "Director 4",
    duration: 95,
    year: 2024,
    description: "This is test description 4",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 10,
    nameRU: "Тестовый фильм 11",
    nameEN: "Test film 4",
  },
];

export const savedMoviesArray = [
  {
    country: "США",
    director: "Director 1",
    duration: 107,
    year: 2022,
    description: "This is test description 1",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 11,
    nameRU: "Сохраненный 1",
    nameEN: "Test film 1",
  },
  {
    country: "США",
    director: "Director 2",
    duration: 87,
    year: 2022,
    description: "This is test description 2",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 12,
    nameRU: "Сохраненный 2",
    nameEN: "Test film 2",
  },
  {
    country: "США",
    director: "Director 3",
    duration: 68,
    year: 2023,
    description: "This is test description 3",
    image: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    trailerLink: "https://www.youtube.com",
    thumbnail: "https://i.postimg.cc/sDQr27MM/pic-COLOR-pic.jpg",
    movieId: 3,
    nameRU: "Сохраненный 3",
    nameEN: "Test film 3",
  },
];
